// <auto-generated />
using System;
using IgrejaV2.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IgrejaV2.Infraestrutura.Migrations
{
    [DbContext(typeof(IgrejaContexto))]
    [Migration("20260510020932_AdicionarTraducaoEVersiculos")]
    partial class AdicionarTraducaoEVersiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<string>("Bairro")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complemento");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Numero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("rua");

                    b.HasKey("Id");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_maxima");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("RequerInscricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requer_inscricao");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_evento_id");

                    b.Property<int?>("endereco_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoEventoId");

                    b.HasIndex("endereco_id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer")
                        .HasColumnName("responsavel_id");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Igreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fundacao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("integer")
                        .HasColumnName("endereco_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("PastorResponsavelId")
                        .HasColumnType("integer")
                        .HasColumnName("pastor_responsavel_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PastorResponsavelId");

                    b.ToTable("igrejas", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acao")
                        .HasColumnType("integer")
                        .HasColumnName("acao");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("dados_anteriores");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("text")
                        .HasColumnName("dados_novos");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Entidade")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entidade");

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("entidade_id");

                    b.Property<int?>("IgrejaId")
                        .HasColumnType("integer")
                        .HasColumnName("igreja_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Patrimonio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aquisicao");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int?>("EstadoConservacao")
                        .HasColumnType("integer")
                        .HasColumnName("estado_conservacao");

                    b.Property<int?>("IgrejaId")
                        .HasColumnType("integer")
                        .HasColumnName("igreja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroPatrimonio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_patrimonio");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("ValorAquisicao")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_aquisicao");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("patrimonios", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_batismo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int?>("EstadoCivil")
                        .HasColumnType("integer")
                        .HasColumnName("estado_civil");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MembroDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("membro_desde");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("pessoas", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.PessoaEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("integer")
                        .HasColumnName("endereco_id");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("pessoas_enderecos", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Presenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Presente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("presente");

                    b.Property<int?>("RegistradoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("registrado_por_id");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("presencas", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int?>("PublicoAlvo")
                        .HasColumnType("integer")
                        .HasColumnName("publico_alvo");

                    b.Property<bool>("RequerPresenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("requer_presenca");

                    b.HasKey("Id");

                    b.ToTable("tipos_evento", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Traducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abreviacao");

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("traducoes", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("IpUltimoLogin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_ultimo_login");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_usuario");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("PrimeiroAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("primeiro_acesso");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_usuario");

                    b.Property<string>("TokenRecuperacaoSenha")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token_recuperacao_senha");

                    b.Property<DateTime?>("TokenRecuperacaoSenhaExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_recuperacao_senha_expiracao");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_usuarios_email");

                    b.HasIndex("NomeUsuario")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_nome_usuario_unique");

                    b.HasIndex("PessoaId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Vericulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int>("Capitulo")
                        .HasColumnType("integer")
                        .HasColumnName("capitulo");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("boolean")
                        .HasColumnName("deletado");

                    b.Property<int?>("DeletadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("deletado_por_id");

                    b.Property<int>("Livro")
                        .HasColumnType("integer")
                        .HasColumnName("livro");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("texto");

                    b.Property<int>("TraducaoId")
                        .HasColumnType("integer")
                        .HasColumnName("traducao_id");

                    b.HasKey("Id");

                    b.HasIndex("TraducaoId");

                    b.HasIndex("Livro", "TraducaoId");

                    b.HasIndex("Livro", "Capitulo", "TraducaoId");

                    b.HasIndex("Livro", "Capitulo", "Numero", "TraducaoId")
                        .IsUnique();

                    b.ToTable("versiculos", (string)null);
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Evento", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_tipos_evento_tipo_evento_id");

                    b.HasOne("IgrejaV2.Dominio.Entidades.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("endereco_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eventos_enderecos_endereco_id");

                    b.Navigation("Endereco");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Familia", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Pessoa", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_familias_pessoas_responsavel_id");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Igreja", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_igrejas_enderecos_endereco_id");

                    b.HasOne("IgrejaV2.Dominio.Entidades.Pessoa", "PastorResponsavel")
                        .WithMany()
                        .HasForeignKey("PastorResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_igrejas_pessoas_pastor_responsavel_id");

                    b.Navigation("Endereco");

                    b.Navigation("PastorResponsavel");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Log", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_logs_igrejas_igreja_id");

                    b.HasOne("IgrejaV2.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_logs_usuarios_usuario_id");

                    b.Navigation("Igreja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Patrimonio", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Igreja", "Igreja")
                        .WithMany("Patrimonios")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_patrimonios_igrejas_igreja_id");

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Pessoa", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pessoas_familias_familia_id");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.PessoaEndereco", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Endereco", "Endereco")
                        .WithMany("PessoasEnderecos")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_enderecos_endereco_id");

                    b.HasOne("IgrejaV2.Dominio.Entidades.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_enderecos_pessoa_id");

                    b.Navigation("Endereco");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Presenca", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Evento", "Evento")
                        .WithMany("Presencas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_presencas_eventos_evento_id");

                    b.HasOne("IgrejaV2.Dominio.Entidades.Pessoa", "Pessoa")
                        .WithMany("Presencas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IgrejaV2.Dominio.Entidades.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_presencas_usuarios_registrado_por_id");

                    b.Navigation("Evento");

                    b.Navigation("Pessoa");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuarios_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Vericulo", b =>
                {
                    b.HasOne("IgrejaV2.Dominio.Entidades.Traducao", "Traducao")
                        .WithMany("Versiculos")
                        .HasForeignKey("TraducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versiculos_traducao_id");

                    b.Navigation("Traducao");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Endereco", b =>
                {
                    b.Navigation("PessoasEnderecos");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Evento", b =>
                {
                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Familia", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Igreja", b =>
                {
                    b.Navigation("Patrimonios");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Pessoa", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.TipoEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("IgrejaV2.Dominio.Entidades.Traducao", b =>
                {
                    b.Navigation("Versiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
